### ISSUE TITLE
블로그 글 상세보기 페이지 404 에러 

### ISSUE THREAD

**Issue by Bang04** [Bang04/Bang04.github.io#1]
## 설명
블로그 리스트 클릭 시 View 페이지를 찾지 못하고 Unhandled Runtime Error 가 발생합니다.
마크다운 파일 Path :  content/blog/*.md   

## 스크린샷
<img width="1254" alt="image" src="https://github.com/Bang04/Bang04.github.io/assets/52026973/fcd3cdd4-4d54-4ad4-a91b-c663e43e1a55">

**Comment by elliekoooo** [comment]
에러페이지에서 보이듯 location이 제대로 안넘어오고 undefined가 뜨네요

**Comment by elliekoooo** [comment]
https://www.gatsbyjs.com/docs/location-data-from-props/
